### ISSUE TITLE
Failed at the reactjs-socket-io-chat-app@0.6.9 start script 'node app.js'

### ISSUE THREAD

**Issue by MuhammadTamzid** [DanialK/ReactJS-Realtime-Chat#4]
after run `npm start` raise this error

> reactjs-socket-io-chat-app@0.6.9 start /home/tamzid/workspace/react/chat_demo
> node app.js

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at Object.<anonymous> (/home/tamzid/workspace/react/chat_demo/app.js:29:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

npm ERR! Linux 3.19.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! reactjs-socket-io-chat-app@0.6.9 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reactjs-socket-io-chat-app@0.6.9 start script 'node app.js'.
npm ERR! This is most likely a problem with the reactjs-socket-io-chat-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reactjs-socket-io-chat-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls reactjs-socket-io-chat-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tamzid/workspace/react/chat_demo/npm-debug.log

**Comment by ribeiroevandro** [comment]
This is looking like permission error, a module is not installed properly, tried to run using sudo or giving permission for your user?
I run here and had no problems, I believe that it can be...

**Comment by ppozniak** [comment]
Isn't `Error: listen EADDRINUSE :::3000` thrown when port 3000 is already in use?

**Comment by Paramchoudhary** [comment]
install node module or copy paste N.M. in the folder.
